name: Build and upload

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.platform.name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Linux (x64)'   ,os: ubuntu-24.04 }
          - { name: 'Linux (arm64)' ,os: ubuntu-24.04 ,arch: arm64 }
          - { name: 'Windows (x64)' ,os: windows-2022 }
          - { name: 'Mac (x64)'     ,os: macos-14 }
          - { name: 'Mac (arm64)'   ,os: macos-14     ,arch: arm64 }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: ./scripts/install-deps-mac.sh

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') && matrix.platform.arch != 'arm64' }}
        run: ./scripts/install-deps-ubuntu.sh

      - if: ${{ !startsWith(matrix.platform.os, 'ubuntu-') || matrix.platform.arch != 'arm64' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROSS_COMPILE_ARCH: ${{ matrix.platform.arch }}
        run: npm run release

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') && matrix.platform.arch == 'arm64' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/release-rpi-qemu.sh
